name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Install renv and rsconnect
        run: |
          install.packages(c("renv", "rsconnect"))
        shell: Rscript {0}
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore and install dependencies through renv
        run: |
          renv::restore()
          install.packages("rsconnect")  # Ensure rsconnect is available for deployment
        shell: Rscript {0}

      - name: Authorize and deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        run: |
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          
          # a list of files to exclude while deploying
          exclude_list <- c("rsconnect/", ".git/", ".github/", ".gitignore", "README.md")
          
          # Deploy with renv but exclude some files and folders
          rsconnect::deployApp(
            appName = "${{ github.event.repository.name }}",
            account = Sys.getenv("SHINYAPPS_ACCOUNT"),
            forceUpdate = TRUE,
            appFiles = NULL,  # Setting to NULL will include all files except those in appFileIgnore
            appFileIgnore = exclude_list,
            appDependencies = TRUE
          )
        shell: Rscript {0}