name: Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Add permissions to read organization secrets
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev
      
      - name: Install renv and rsconnect
        run: |
          install.packages(c("renv", "rsconnect"))
        shell: Rscript {0}
        
      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore and install dependencies through renv
        run: |
          renv::restore()
          install.packages("rsconnect")
        shell: Rscript {0}

      - name: Authorize and deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        run: |
          # Debug: Check if environment variables are set
          cat <<EOF | bash
          echo "Token exists: $([ ! -z "$SHINYAPPS_TOKEN" ] && echo "Yes" || echo "No")"
          echo "Secret exists: $([ ! -z "$SHINYAPPS_SECRET" ] && echo "Yes" || echo "No")"
          echo "Account exists: $([ ! -z "$SHINYAPPS_ACCOUNT" ] && echo "Yes" || echo "No")"
          EOF
          
          # Set account info 
          token <- Sys.getenv("SHINYAPPS_TOKEN")
          secret <- Sys.getenv("SHINYAPPS_SECRET")
          account <- Sys.getenv("SHINYAPPS_ACCOUNT")
          
          # Show account name
          cat("Using account name:", account, "\n")
          
          # Validating the authentication info
          if (token == "" || secret == "" || account == "") {
            stop("Missing shinyapps.io authentication information. Please check your organization secrets.")
          }
          
          rsconnect::setAccountInfo(
            name = account,
            token = token,
            secret = secret
          )
          
          # a list of files to exclude (rsconnect folder and any other unwanted files)
          exclude_list <- c("rsconnect/", ".git/", ".github/", ".gitignore", "README.md")
          
          # Deploy with renv but exclude the rsconnect folder
          rsconnect::deployApp(
            appName = "${{ github.event.repository.name }}",
            account = account,
            forceUpdate = TRUE,
            appFiles = NULL,  # Setting to NULL will include all files except those in appFileIgnore
            appFileIgnore = exclude_list,
            appDependencies = TRUE
          )
        shell: Rscript {0}